### ISSUE TITLE
API documentation duplicates

### ISSUE THREAD

**Issue by cwolcott** [neuhausi/canvasXpress#182]
The API documentation has a duplicate entry for 

- **Aspect Ratio, Space and Width** and **Aspect Ratio, Space and width**
![Image](https://github.com/user-attachments/assets/150e5093-fbd8-4ece-b701-ca2ee4df1f9e)

- **Plot Area** and **Plot area**
![Image](https://github.com/user-attachments/assets/becd7c8e-2da7-4c21-b312-acd3b47f304f)

**Comment by neuhausi** [comment]
Fixed in Version 53.9.
Thank you

**Comment by neuhausi** [comment]
Please check in version 54.0 and close

**Comment by cwolcott** [comment]
The duplicate **Plot Area** menu item is been removed.

But the duplicate **Aspect Ratio, Space and Width** still exists.

![Image](https://github.com/user-attachments/assets/ad935c1b-6bf7-4e34-9c52-3d12f51a81dd)

**Comment by neuhausi** [comment]
Arghhh. Fixed in next version. Thank you

**Comment by cwolcott** [comment]
Fixed in 54.1
